### ISSUE TITLE
Change CLI arguments to a config file

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicode/agent-plugin-builder#7]
# Description

Since this tool uses CLI arguments to do a lot of things we should probably move to a config file which will be specified in the plugin's directories. That config file will need to be configured per plugin and the only command to run will be `build_agent_plugin .`. We didn't do that in the first place because we thought that the first thing anyone will look at will be CLI arguments to configure.

# Tasks
- [ ] Create `AgentPluginOptions` pydantic model with needed fields ( same as we have for CLI arguments )
- [ ] Read plugin's `build.{yaml, yml}` and validate it to `AgentPluginOptions`
- [ ] Use those options everywhere where needed
